# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: exothermic-story-mapping
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
    # Build dependencies
    - make build-deps
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
    - image_templates: ["stevenweathers/exothermic-story-mapping:{{ .Tag }}-amd64"]
      binaries: [exothermic-story-mapping]
      dockerfile: "build/gorDockerfile"
      use_buildx: true
      build_flag_templates:
      - --platform=linux/amd64
    - image_templates: ["stevenweathers/exothermic-story-mapping:{{ .Tag }}-arm64v8"]
      binaries: [exothermic-story-mapping]
      goarch: arm64
      dockerfile: "build/gorDockerfile"
      use_buildx: true
      build_flag_templates:
      - --platform=linux/arm64/v8
    - image_templates: ["stevenweathers/exothermic-story-mapping:latest-amd64"]
      binaries: [exothermic-story-mapping]
      dockerfile: "build/gorDockerfile"
      use_buildx: true
      build_flag_templates:
      - --platform=linux/amd64
    - image_templates: ["stevenweathers/exothermic-story-mapping:latest-arm64v8"]
      binaries: [exothermic-story-mapping]
      goarch: arm64
      dockerfile: "build/gorDockerfile"
      use_buildx: true
      build_flag_templates:
      - --platform=linux/arm64/v8
docker_manifests:
    - name_template: stevenweathers/exothermic-story-mapping:latest
      image_templates:
      - stevenweathers/exothermic-story-mapping:latest-amd64
      - stevenweathers/exothermic-story-mapping:latest-arm64v8
    - name_template: stevenweathers/exothermic-story-mapping:{{ .Tag }}
      image_templates:
      - stevenweathers/exothermic-story-mapping:{{ .Tag }}-amd64
      - stevenweathers/exothermic-story-mapping:{{ .Tag }}-arm64v8
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dist: release