# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: exothermic-story-mapping
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
    # Build dependencies
    - make build-deps
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
    - image_templates: 
      - "stevenweathers/{{.ProjectName}}:{{ .Tag }}-amd64"
      - "stevenweathers/{{.ProjectName}}:latest-amd64"
      - "ghcr.io/stevenweathers/{{.ProjectName}}:{{ .Tag }}-amd64"
      - "ghcr.io/stevenweathers/{{.ProjectName}}:latest-amd64"
      dockerfile: "build/gorDockerfile"
      use_buildx: true
      build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/StevenWeathers/{{.ProjectName}}
      - --label=org.opencontainers.image.source=https://github.com/StevenWeathers/{{.ProjectName}}
    - image_templates: 
      - "stevenweathers/{{.ProjectName}}:{{ .Tag }}-arm64v8"
      - "stevenweathers/{{.ProjectName}}:latest-arm64v8"
      - "ghcr.io/stevenweathers/{{.ProjectName}}:{{ .Tag }}-arm64v8"
      - "ghcr.io/stevenweathers/{{.ProjectName}}:latest-arm64v8"
      goarch: arm64
      dockerfile: "build/gorDockerfile"
      use_buildx: true
      build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/StevenWeathers/{{.ProjectName}}
      - --label=org.opencontainers.image.source=https://github.com/StevenWeathers/{{.ProjectName}}
docker_manifests:
    - name_template: stevenweathers/{{.ProjectName}}:latest
      image_templates:
      - stevenweathers/{{.ProjectName}}:latest-amd64
      - stevenweathers/{{.ProjectName}}:latest-arm64v8
    - name_template: stevenweathers/{{.ProjectName}}:{{ .Tag }}
      image_templates:
      - stevenweathers/{{.ProjectName}}:{{ .Tag }}-amd64
      - stevenweathers/{{.ProjectName}}:{{ .Tag }}-arm64v8
    - name_template: ghcr.io/stevenweathers/{{.ProjectName}}:latest
      image_templates:
      - ghcr.io/stevenweathers/{{.ProjectName}}:latest-amd64
      - ghcr.io/stevenweathers/{{.ProjectName}}:latest-arm64v8
    - name_template: ghcr.io/stevenweathers/{{.ProjectName}}:{{ .Tag }}
      image_templates:
      - ghcr.io/stevenweathers/{{.ProjectName}}:{{ .Tag }}-amd64
      - ghcr.io/stevenweathers/{{.ProjectName}}:{{ .Tag }}-arm64v8
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dist: release